import animation.customComponents.AnimatedPanel;
import animation.AnimationManager;
import animation.Event; // Import Event class
import animation.Shader;

import java.awt.Color;

import javax.swing.*;

/**
 EXAMPLE GENERATED BY GEMINI, REFINED BY ME(jeff)(cuz it doesn't know how to use my lib bruh)
 Green comments are written by ME, normal gray comments is generated by gemini
 shader implementation by ME (sebastian)
 */
public class ExampleGUI extends JFrame {

    private final AnimationManager animationManager; // Make animationManager a field
    private final JButton button; // Make button a field
    private final AnimatedPanel animatedPanel; // The panel that will be animated
    private final JPanel panel; // The main panel

    public ExampleGUI() {
        setTitle("Animation Example");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        panel = new JPanel(null); // Using null layout for manual positioning
        add(panel);

        button = new JButton("Click me!");
        button.setBounds(50, 50, 100, 30);
        panel.add(button);

        animatedPanel = new AnimatedPanel();
        animatedPanel.setBounds(400, 200, 150, 100);
        panel.add(animatedPanel);
            Shader shader = new Shader(this);
            shader.applyWave(1, 1, 3);;
            shader.setColorFilter(new Color(0, 255, 255, 50));



        animationManager = new AnimationManager(0); // Initialize AnimationManager with a custom update interval
        /**
         * The update interval represents how many milliseconds it waits to update all animations again
         * Generally lower value is smoother, but consumes more resources. Don't set to negative
         */

        // Animate the button after a delay
        animationManager.getEventManager().addEvent(new Event(1f, () -> {
            animationManager.animateMove(button, 250, 100, 2, AnimationManager.Easing.EASE_IN_OUT_CUBIC);
        }));
        /**
         * This sets a function that triggers after triggerTime SECONDS (triggertime is a float, measured in seconds)
         * eventManager automatically initializes WITH animationManager
         */

        // Animate the custom panel
        animationManager.getEventManager().addEvent(new Event(0.5f, () -> animationManager.animateFade(animatedPanel, 0.0f, 1.5f, AnimationManager.Easing.EASE_IN_SINE)));
        animationManager.getEventManager().addEvent(new Event(2.5f, () -> animationManager.animateFade(animatedPanel, 1.0f, 1.5f, AnimationManager.Easing.EASE_OUT_SINE)));
        animationManager.getEventManager().addEvent(new Event(0.5f, () -> animationManager.animateRotation(animatedPanel, 360f, 4f, AnimationManager.Easing.EASE_IN_OUT_CUBIC)));
        // Example of scaling: Make the panel grow and then shrink back.
        // The scale parameter is a factor (e.g., 1.2 is 120%).
        animationManager.getEventManager().addEvent(new Event(3f, () -> animationManager.animateScale(animatedPanel, 5f, 5f, 1f, AnimationManager.Easing.EASE_OUT_QUAD)));
        animationManager.getEventManager().addEvent(new Event(5f, () -> animationManager.animateScale(animatedPanel, 0.2f, 0.2f, 1f, AnimationManager.Easing.EASE_IN_QUAD)));


        // Add events to the EventManager
        animationManager.getEventManager().addEvent(new Event(1.5f, () -> {
            button.setText("Event 1 triggered!");
            System.out.println("Event 1 triggered at 1.5 seconds!");
        }));

        animationManager.getEventManager().addEvent(new Event(3.5f, () -> {
            button.setText("Event 2 triggered!");
            System.out.println("Event 2 triggered at 3.5 seconds!");
        }));

        animationManager.getEventManager().addEvent(new Event(7.0f, () -> {
            button.setText("Animation and Events done!");
            System.out.println("All animations and events finished at 7.0 seconds!");
            animationManager.stop(); // Stop the animation manager
        }));
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            ExampleGUI ex = new ExampleGUI();
            ex.setVisible(true);
        });
    }
}
