import animation.Utils;
import animation.customComponents.AnimatedLabel;
import animation.customComponents.AnimatedPanel;
import animation.AnimationManager;
import animation.Event; // Import Event class

import javax.swing.*;
import java.awt.*;
import java.util.Objects;

/**
 EXAMPLE GENERATED BY GEMINI, REFINED BY ME(cuz it doesn't know how to use my lib bruh)
 Green comments are written by ME, normal gray comments is generated by gemini
 */
public class ExampleGUI extends JFrame {

    private final AnimationManager animationManager; // Make animationManager a field
    private JButton button = null; // Make button a field
    private AnimatedPanel animatedPanel = null; // The panel that will be animated

    public ExampleGUI(int type) {
        setTitle("Animation Example");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel(null); // Using null layout for manual positioning
        add(panel);

        animationManager = new AnimationManager(5); // Initialize AnimationManager with a custom update interval
        /**
         * The update interval represents how many milliseconds it waits to update all animations again
         * Generally lower value is smoother, but consumes more resources. Don't set to negative
         * Zero is basically "run as fast as you can"
         */

        if (type == 69420) {
            panel.setBackground(new Color(0.15f, 0.15f, 0.2f, 1f));

            AnimatedLabel focus = new AnimatedLabel();
            int scaledWidth = (int)(589 * 2.1);
            int scaledHeight = (int)(295 * 2.1);

            focus.setIcon(new ImageIcon(Utils.resizeTo(
                    new ImageIcon(Objects.requireNonNull(ExampleGUI.class.getResource("/assets/focus.png"))).getImage(),
                    scaledWidth, scaledHeight)));

            focus.setBounds(400 - scaledWidth / 2, 300 - scaledHeight / 2, scaledWidth, scaledHeight);
            focus.setOpacity(0f);
            panel.add(focus);

            AnimatedLabel gdxLogo = new AnimatedLabel();
            gdxLogo.setIcon(new ImageIcon(Utils.resizeTo(
                    new ImageIcon(Objects.requireNonNull(ExampleGUI.class.getResource("/assets/madeWLibGDX.png"))).getImage(),
                    100.0)));
            gdxLogo.setBounds(400 - 454 / 2, 300 - 126 / 2, 454, 126);
            gdxLogo.setOpacity(0f);
            animationManager.animateScale(gdxLogo, 0.1f, 0.1f, 0.1f, AnimationManager.Easing.LINEAR);
            panel.add(gdxLogo);

            AnimatedLabel allRoadsLeadToRome = new AnimatedLabel();
            allRoadsLeadToRome.setIcon(new ImageIcon(Objects.requireNonNull(ExampleGUI.class.getResource("/assets/time_ticking.png"))));
            allRoadsLeadToRome.setBounds(400 - allRoadsLeadToRome.getPreferredSize().width / 2 + 700, 300 - allRoadsLeadToRome.getPreferredSize().height / 2, allRoadsLeadToRome.getPreferredSize().width, allRoadsLeadToRome.getPreferredSize().height);
            allRoadsLeadToRome.setOpacity(0f);
            panel.add(allRoadsLeadToRome);

            AnimatedLabel logo = new AnimatedLabel();
            logo.setIcon(new ImageIcon(Utils.resizeTo(new ImageIcon(Objects.requireNonNull(ExampleGUI.class.getResource("/assets/grease_up.png"))).getImage(), 120)));
            logo.setBounds(400 - 120 / 2, 300 - 120 / 2 - 600, 120, 120);
            panel.add(logo);

            AnimatedPanel flash = new AnimatedPanel(Color.WHITE);
            flash.setBounds(0, 0, 800, 600);
            flash.setOpacity(0f);
            panel.add(flash);

            ////////////
            //CUTSCENE//
            ////////////

            // Sound: introSong = Gdx.audio.newMusic(Gdx.files.internal("audio/give-it-one.mp3"));
            // Sound: introSong.setLooping(false);
            // Sound: introSong.setVolume(1f);
            // Sound: introSong.setPosition(2);

            // Sound: bgm = Gdx.audio.newMusic(Gdx.files.internal("audio/elevator-music-fix.mp3"));
            // Sound: bgm.setLooping(true);
            // Sound: bgm.setVolume(0f);

            animationManager.getEventManager().addEvent(new Event(1f, () -> {
                animationManager.animateScale(gdxLogo, 10f, 10f, 8f, AnimationManager.Easing.EASE_IN_OUT_EXPO);
                animationManager.animateFade(gdxLogo, 1f, 5f, AnimationManager.Easing.EASE_IN_OUT_QUAD);
                // Sound: introSong.play();
            }));
            animationManager.getEventManager().addEvent(new Event(3f, () -> {
                animationManager.animateMove(logo, logo.getX(), logo.getY() + 600, 6f, AnimationManager.Easing.EASE_IN_OUT_ELASTIC);
            }));
            animationManager.getEventManager().addEvent(new Event(4.67f, () -> {
                animationManager.animateFade(flash, 1f, 0.3f, AnimationManager.Easing.LINEAR);
            }));
            animationManager.getEventManager().addEvent(new Event(5f, () -> {
                animationManager.animateRotation(gdxLogo, -15f, 5f, AnimationManager.Easing.EASE_OUT_QUAD);
                animationManager.animateMove(gdxLogo, gdxLogo.getX() - 300, gdxLogo.getY() - 150, 5f, AnimationManager.Easing.EASE_IN_OUT_CUBIC);
                animationManager.animateFade(focus, 0.67f, 3f, AnimationManager.Easing.EASE_IN_OUT_EXPO);
                animationManager.animateFade(allRoadsLeadToRome, 1f, 3f, AnimationManager.Easing.EASE_IN_OUT_EXPO);
                animationManager.animateMove(allRoadsLeadToRome, allRoadsLeadToRome.getX() - 250, allRoadsLeadToRome.getY(), 3f, AnimationManager.Easing.EASE_IN_OUT_SINE);
            }));
            animationManager.getEventManager().addEvent(new Event(5.5f, () -> {
                animationManager.animateFade(flash, 0f, 3f, AnimationManager.Easing.LINEAR);
            }));
            animationManager.getEventManager().addEvent(new Event(9f, () -> {
                animationManager.animateScale(gdxLogo, 1f - 1f / 5f, 1f - 1f / 5f, 3f, AnimationManager.Easing.EASE_IN_OUT_EXPO);
                animationManager.animateMove(logo, logo.getX() - 200, logo.getY() - 100, 3f, AnimationManager.Easing.EASE_IN_OUT_BACK);
                animationManager.animateScale(logo, 1f - 1f / 5f, 1f - 1f / 5f, 3.5f, AnimationManager.Easing.EASE_IN_OUT_BACK);
                // Skipped animating "drink" sprite.
            }));
            animationManager.getEventManager().addEvent(new Event(10f, () -> {
                // Sound: introSong.setVolume(0.90f);
                animationManager.animateRotation(gdxLogo, -20f, 9999f * 3, AnimationManager.Easing.EASE_OSCILLATE_INFINITE);
                animationManager.animateFade(logo, 0.5f, 9999f * 3, AnimationManager.Easing.EASE_OSCILLATE_INFINITE);
                animationManager.animateMove(allRoadsLeadToRome, allRoadsLeadToRome.getX() + 50, allRoadsLeadToRome.getY() + 10, 9999f * 3, AnimationManager.Easing.EASE_OSCILLATE_INFINITE);
                animationManager.animateFade(focus, 1f, 9999f * 3, AnimationManager.Easing.EASE_OSCILLATE_INFINITE);
            }));
        } else {
            button = new JButton("Click me!");
            button.setBounds(50, 50, 100, 30);
            panel.add(button);

            animatedPanel = new AnimatedPanel(Color.BLUE);
            animatedPanel.setBounds(400, 200, 150, 100);
            panel.add(animatedPanel);

            // Animate the button after a delay
            animationManager.getEventManager().addEvent(new Event(1f, () -> {
                animationManager.animateMove(button, 250, 100, 2, AnimationManager.Easing.EASE_IN_OUT_CUBIC);
            }));
            /**
             * This sets a function that triggers after triggerTime SECONDS (triggertime is a float, measured in seconds)
             * eventManager automatically initializes WITH animationManager
             */

            // Animate the custom panel
            animationManager.getEventManager().addEvent(new Event(0.5f, () -> animationManager.animateFade(animatedPanel, 0.0f, 1.5f, AnimationManager.Easing.EASE_IN_SINE)));
            animationManager.getEventManager().addEvent(new Event(2.5f, () -> animationManager.animateFade(animatedPanel, 1.0f, 1.5f, AnimationManager.Easing.EASE_OUT_SINE)));
            animationManager.getEventManager().addEvent(new Event(0.5f, () -> animationManager.animateRotation(animatedPanel, 360f, 4f, AnimationManager.Easing.EASE_IN_OUT_CUBIC)));
            // Example of scaling: Make the panel grow and then shrink back.
            // The scale parameter is a factor (e.g., 1.2 is 120%).
            animationManager.getEventManager().addEvent(new Event(3f, () -> animationManager.animateScale(animatedPanel, 5f, 5f, 1f, AnimationManager.Easing.EASE_OUT_QUAD)));
            animationManager.getEventManager().addEvent(new Event(5f, () -> animationManager.animateScale(animatedPanel, 0.2f, 0.2f, 1f, AnimationManager.Easing.EASE_IN_QUAD)));


            // Add events to the EventManager
            animationManager.getEventManager().addEvent(new Event(1.5f, () -> {
                button.setText("Event 1 triggered!");
                System.out.println("Event 1 triggered at 1.5 seconds!");
            }));

            animationManager.getEventManager().addEvent(new Event(3.5f, () -> {
                button.setText("Event 2 triggered!");
                System.out.println("Event 2 triggered at 3.5 seconds!");
            }));

            animationManager.getEventManager().addEvent(new Event(7.0f, () -> {
                button.setText("Animation and Events done!");
                System.out.println("All animations and events finished at 7.0 seconds!");
                animationManager.stop(); // Stop the animation manager
            }));
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            ExampleGUI ex = new ExampleGUI(69420);
            ex.setVisible(true);
        });
    }
}
